receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  logging:
    loglevel: debug

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging] # For now, just log traces. Can add Jaeger/Tempo here.
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]